### ISSUE TITLE
Fail to start on Ubuntu 18.04

### ISSUE THREAD

**Issue by quozl** [godiard/music-keyboard-activity#20]
Music Keyboard does not start on Ubuntu 18.04, with logs showing

```
/usr/lib/libcsound64.so.6.0(+0x3f7e3) [0x7f70d65d77e3]
/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7f70e9767f20]
/usr/lib/libcsound64.so.6.0(+0x258014) [0x7f70d67f0014]
/usr/lib/libcsound64.so.6.0(+0x272601) [0x7f70d680a601]
/usr/lib/libcsound64.so.6.0(+0x26ee34) [0x7f70d6806e34]
/usr/lib/libcsound64.so.6.0(+0x26eecb) [0x7f70d6806ecb]
/usr/lib/libcsound64.so.6.0(csoundParseOrc+0x2d7) [0x7f70d68126b7]
/usr/lib/libcsound64.so.6.0(+0x27a087) [0x7f70d6812087]
/usr/lib/libcsound64.so.6.0(csoundCompileCsdText+0x5f) [0x7f70d673e37f]
/usr/lib/libcsound64.so.6.0(csoundCompileCsd+0x3b) [0x7f70d673e47b]
/usr/lib/python2.7/dist-packages/_csnd6.x86_64-linux-gnu.so(+0x4bc6e) [0x7f70d6d43c6e]
...
Csound tidy up: Segmentation fault
```

and `gdb` backtrace reproduced repeatedly showing

```
gdb `which python`
(gdb) run /usr/bin/sugar-activity
(gdb) bt
#0  0x00007fffe8b5c014 in make_label (csound=csound@entry=0x55555669f800, s=s@entry=0x5555569f0680 "__synthetic_300") at ./Engine/csound_orc.lex:586 
#1  0x00007fffe8b76601 in create_synthetic_label (count=300, csound=0x55555669f800) 
    at ../Engine/csound_orc_expressions.c:848 
#2  0x00007fffe8b76601 in expand_if_statement (csound=csound@entry=0x55555669f800, current=current@entry=0x5555568b2410, typeTable=typeTable@entry=0x55555680e470) 
    at ../Engine/csound_orc_expressions.c:1156 
#3  0x00007fffe8b72e34 in verify_tree (csound=csound@entry=0x55555669f800, root=<optimised out>, typeTable=typeTable@entry=0x55555680e470) at ../Engine/csound_orc_semantics.c:1813 
#4  0x00007fffe8b72ecb in verify_tree (csound=csound@entry=0x55555669f800, root=<optimised out>, typeTable=typeTable@entry=0x55555680e470) at ../Engine/csound_orc_semantics.c:1787 
#5  0x00007fffe8b7e6b7 in csoundParseOrc (csound=csound@entry=0x55555669f800, str=str@entry=0x0) at ../Engine/new_orc_parser.c:258 
#6  0x00007fffe8b7e087 in csoundCompileOrcInternal (csound=csound@entry=0x55555669f800, str=str@entry=0x0, async=async@entry=0) at ../Engine/csound_orc_compile.c:1827 
#7  0x00007fffe8aaa37f in csoundCompileCsdText (csound=csound@entry=0x55555669f800, csd_text=<optimised out>) at ../Top/main.c:530 
#8  0x00007fffe8aaa47b in csoundCompileCsd (csound=0x55555669f800, str=<optimised out>) 
    at ../Top/main.c:516 
#9  0x00007fffe90afc6e in Csound::CompileCsd(char const*) (csd=<optimised out>, this=0x5555564fbb80) at .././include/csound.hpp:259 
#10 0x00007fffe90afc6e in _wrap_Csound_CompileCsd(PyObject*, PyObject*) (args=<optimised out>) at python_interfacePYTHON_wrap.cxx:25886 
#11 0x000055555564901a in PyEval_EvalFrameEx () 
...
```

Other segmentation faults are easily reproduced using python, with the simplest reproducer being

```python
import csnd6
a = csnd6.Csound()
a.Start()
b = csnd6.CsoundPerformanceThread(a)
b.Play()
```

which generates this repeatable `gdb` backtrace

```
#0  0x00007ffff5a36c04 in spoutsf (csound=0x555555c4c3c0) at ../InOut/libsnd.c:79
#1  0x00007ffff5a066fb in kperf_nodebug (csound=0x555555c4c3c0) at ../Top/csound.c:1761
#2  0x00007ffff5a07f2e in csoundPerformKsmps (csound=0x555555c4c3c0)
    at ../Top/csound.c:2113
#3  0x00007ffff5f124b6 in CsoundPerformanceThread::Perform (this=0x555555e3bf40)
    at ../interfaces/csPerfThread.cpp:434
#4  0x00007ffff5f12778 in CsPerfThread_PerformScore::Perform (this=<synthetic pointer>)
    at ../interfaces/csPerfThread.cpp:483
#5  csoundPerformanceThread_ (userData=<optimised out>)
    at ../interfaces/csPerfThread.cpp:500
#6  0x00007ffff77cc6db in start_thread (arg=0x7fffe8505700) at pthread_create.c:463
#7  0x00007ffff7b0588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

On the face of this evidence, it looks like memory corruption inside Csound, so I'll take it upstream with them.

**Comment by quozl** [comment]
Not a problem with Music Keyboard.

Was fixed in Csound upstream by https://github.com/csound/csound/commit/df5658cd30f60f7caf50650bfdbfd0f480139f43.

Discussion was in Csound issue 948.
