### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by chimosky** [godiard/music-keyboard-activity#27]
Activity fails to start in sugar live build with sugar 0.116, error in logs:
```
Traceback (most recent call last):
  File "/usr/bin/sugar-activity3", line 5, in <module>
    activityinstance.main()
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activityinstance.py", line 179, in main
    module = __import__(module_name)
  File "/home/ibiam/Activities/music-keyboard-activity/activity.py", line 60, in <module>
    from ttcommon.Util.CSoundClient import new_csound_client
  File "/home/ibiam/Activities/music-keyboard-activity/ttcommon/Util/CSoundClient.py", line 5, in <module>
    import ctcsound
ModuleNotFoundError: No module named 'ctcsound'
```

**Comment by quozl** [comment]
Missing dependency.  Install the package [python3-csound](https://packages.debian.org/search?keywords=python3-csound), which, at the time I write, is only available on Debian Testing.

Or, use the r11 branch, per [https://github.com/godiard/music-keyboard-activity/blob/master/README.md](README.md).

Putting it another way, the activity _master_ branch has moved beyond what is available from Sugar Live Build and the Debian Stable release.
